; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-n16r8]
platform = https://github.com/Jason2866/platform-espressif32.git#_Arduino/IDF55
board       = esp32-s3-devkitc-1
framework   = arduino

lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	https://github.com/mrcodetastic/GFX_Lite

; --- memory & partitions to match N16R8 (16MB flash, 8MB PSRAM) ---
board_build.arduino.memory_type = qio_opi ; OPI PSRAM for 8MB configs
board_build.psram_type = opi
board_upload.flash_size = 16MB ; optional: make the upload tool use 16MB flash size explicitly
board_build.arduino.partitions  = default_16MB.csv ; 16MB flash layout

build_flags =
	-DBOARD_HAS_PSRAM ; enable PSRAM code paths

; serial/monitor settings
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_protocol = esptool
upload_speed = 921600
check_skip_packages = yes